const caminho_imagens = '/imagens/perfil';

export default imagens = [
	caminho_imagens + '/alegre.png',
	caminho_imagens + '/amor.png',
	caminho_imagens + '/beijo.png',
	caminho_imagens + '/bravo.png',
	caminho_imagens + '/cansado.png',
	caminho_imagens + '/chorao.png',
	caminho_imagens + '/choro.png',
	caminho_imagens + '/depre.png',
	caminho_imagens + '/desespero.png',
	caminho_imagens + '/doente.png',
	caminho_imagens + '/envergonhado.png',
	caminho_imagens + '/feliz.png',
	caminho_imagens + '/feliz2.png',
	caminho_imagens + '/humilde.png',
	caminho_imagens + '/lagrima.png',
	caminho_imagens + '/lingua.png',
	caminho_imagens + '/lingua2.png',
	caminho_imagens + '/negativo.png',
	caminho_imagens + '/perdido.png',
	caminho_imagens + '/piscar.png',
	caminho_imagens + '/risada.png',
	caminho_imagens + '/sono.png',
	caminho_imagens + '/sorriso.png',
	caminho_imagens + '/surpreso.png',
	caminho_imagens + '/timidez.png',
	caminho_imagens + '/triste.png',

];